name: developement-server
on: [push, workflow_dispatch]
env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    env:
      PORT: ${{secrets.PORT}}
      MONGO_URL: ${{secrets.MONGO_URL}}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node_modules-${{hashFiles('package.json')}}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        continue-on-error: true
        run: npm install
      - name: testing
        run: npm run test-watch -- --watchAll=false
  deploy:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node_modules-${{hashFiles('package.json')}}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        continue-on-error: true
        run: npm install
      - name: login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: build image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/nasa-project .
      - name: push image
        run: docker push ${{ env.DOCKER_USERNAME }}/nasa-project
